#--------------------------------------
--- # Data Source Properties
#--------------------------------------
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/auth-service
        username: postgres
        password: pgsqlpassword1
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
#--------------------------------------
--- # APP Properties
#--------------------------------------
irfanadios:
    app:
        jwtSecret: AL374nDr0p0E72aM4h3nDrAAL374nDr0p0E72aM4h3nDrAAL374nDr0p0E72aM4h3nDrA
        jwtExpirationMs: 900000
        jwtRefreshExpirationMs: 4233600000
